MotoVernal/ViewModels/SectionsAndTopicsListViewModel.cs
using BusinessLogic.DTO.Section;
using BusinessLogic.DTO.Topic;

namespace MotoVernal.ViewModels
{
    public class SectionsAndTopicsListViewModel
    {
        public GetSectionDTO SectionInfo { get; set; }
        public List<GetSectionDTO> ChildSections { get; set; }
        public List<GetSectionDTO> ParentSections { get; set; }
        public List<GetTopicDTO> TopicsList { get; set; }
    }
}

MotoVernal/Controllers/ForumController.cs
using BusinessLogic.DTO.Section;
using BusinessLogic.DTO.Topic;
using BusinessLogic.DTO.TopicResponse;
using BusinessLogic.Errors;
using BusinessLogic.Services.Interfaces;
using DB.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using MotoVernal.Authorizations.Requirements;
using MotoVernal.ViewModels;
using System.Globalization;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace MotoVernal.Controllers
{
    public class ForumController : Controller
    {
        private readonly ISectionService _sectionService;
        private readonly ITopicService _topicService;
        private readonly ITopicResponseService _topicResponseService;
        private readonly IBanService _banService;
        private readonly UserManager<User> _userManager;
        private readonly IAuthorizationService _authorizationService;
        private readonly ITopicResponseReactionService _topicResponseReactionService;

        public ForumController(ISectionService sectionService, ITopicService topicService, ITopicResponseService topicResponseService, IBanService banService, UserManager<User> userManager, IAuthorizationService authorizationService, ITopicResponseReactionService topicResponseReactionService)
        {
            _sectionService = sectionService;
            _topicService = topicService;
            _topicResponseService = topicResponseService;
            _banService = banService;
            _userManager = userManager;
            _authorizationService = authorizationService;
            _topicResponseReactionService = topicResponseReactionService;
        }
        public async Task<IActionResult> SectionsAndTopicsList(int? sectionId, string sortBySection, string? searchSection,
                                                   string sortByTopic, string? searchTopic, DateTime? dateFrom, DateTime? dateTo,
                                                   bool? owner, bool? member)
        {

            var rootSectionResult = _sectionService.GetRootSection();
            if (!rootSectionResult.IsSuccess)
            {
                TempData["ErrorMessage"] = "Root section not found";
                return RedirectToAction("Error", "Home");
            }

            var activeSectionId = sectionId ?? rootSectionResult.Value.Id;

            ViewBag.IsRootSection = activeSectionId == rootSectionResult.Value.Id;

            var sectionInfo = _sectionService.Get(activeSectionId);
            var childSections = _sectionService.GetChildrenSections(activeSectionId);
            var parentSections = _sectionService.GetParentSections(activeSectionId);
            var topics = _topicService.GetAllInSections(activeSectionId);

            if (childSections.Value.Count() == 0)
            {
                ViewBag.NoChildrenSections = true;
            }
            else
            {
                ViewBag.NoChildrenSections = false;
            }
            if (!string.IsNullOrEmpty(searchSection))
            {
                childSections = childSections.Value.Where(section =>
                    !string.IsNullOrEmpty(section.Title) && section.Title.Contains(searchSection, StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }
            switch (sortBySection)
            {
                case "alphabetical_asc":
                    childSections = childSections.Value.OrderBy(s => s.Title).ToList();
                    break;
                case "alphabetical_desc":
                    childSections = childSections.Value.OrderByDescending(s => s.Title).ToList();
                    break;
                default:
                    childSections = childSections.Value.OrderBy(s => s.Title).ToList();
                    break;
            }
            var currentUser = await _userManager.GetUserAsync(User);
            if (currentUser != null)
            {
                if (owner.HasValue && owner.Value || member.HasValue && member.Value)
                {
                    topics = topics.Where(topic =>
                        currentUser.Id != null &&
                        (
                            owner.HasValue && owner.Value && topic.Publisher?.Id == currentUser.Id ||
                            member.HasValue && member.Value && topic.Responses.Any(comment => comment.Owner.Id == currentUser.Id)
                        )
                    ).ToList();
                }
            }
            if (!string.IsNullOrEmpty(searchTopic))
            {
                topics = topics.Where(topic =>
                    !string.IsNullOrEmpty(topic.Title) && topic.Title.Contains(searchTopic, StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }
            if (dateFrom.HasValue)
            {
                topics = topics.Where(t => t.CreationTime >= dateFrom.Value).ToList();
            }
            if (dateTo.HasValue)
            {
                topics = topics.Where(t => t.CreationTime <= dateTo.Value).ToList();
            }
            switch (sortByTopic)
            {
                case "alphabetical_asc":
                    topics = topics.OrderBy(t => t.Title).ToList();
                    break;
                case "alphabetical_desc":
                    topics = topics.OrderByDescending(t => t.Title).ToList();
                    break;
                case "date_asc":
                    topics = topics.OrderBy(t => t.CreationTime).ToList();
                    break;
                case "date_desc":
                    topics = topics.OrderByDescending(t => t.CreationTime).ToList();
                    break;
                default:
                    topics = topics.OrderBy(t => t.CreationTime).ToList();
                    break;
            }
            var vm = new SectionsAndTopicsListViewModel
            {
                SectionInfo = sectionInfo.Value,
                ChildSections = childSections.Value,
                ParentSections = parentSections.Value,
                TopicsList = topics
            };
            ViewBag.SortBySection = sortBySection;
            ViewBag.SearchSection = searchSection;
            ViewBag.SortByTopic = sortByTopic;
            ViewBag.SearchTopic = searchTopic;
            ViewBag.DateFrom = dateFrom?.ToString("yyyy-MM-ddTHH:mm");
            ViewBag.DateTo = dateTo?.ToString("yyyy-MM-ddTHH:mm");
            ViewBag.Owner = owner;
            ViewBag.Member = member;

            return View(vm);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult AddSection(int sectionId)
        {
            var parentSection = _sectionService.GetOne(sectionId);
            if (parentSection == null)
            {
                TempData["ErrorMessage"] = "Parent section not found";
                return RedirectToAction("Error", "Home");
            }
            var model = new AddSectionDTO
            {
                Title = string.Empty,
                Parent = parentSection,
                Image = null
            };
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult AddSection(AddSectionDTO model)
        {
            var parentSection = _sectionService.GetOne(model.Parent.Id);
            model.Parent = parentSection;
            if (model.Image?.Base64 == "defaultBase64Value" && model.Image?.Extension == "defaultExtension")
            {
                model.Image = null;
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            _sectionService.Add(model);
            return RedirectToAction("SectionsAndTopicsList", new { sectionId = model.Parent.Id });
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult EditSection(int Id)
        {
            var sectionToEdit = _sectionService.GetOne(Id);
            if (sectionToEdit == null)
            {
                TempData["ErrorMessage"] = "Section of this id not found";
                return RedirectToAction("Error", "Home");
            }
            var model = new UpdateSectionDTO
            {
                Id = sectionToEdit.Id,
                Title = sectionToEdit.Title,
                Parent = sectionToEdit.Parent,
                Image = sectionToEdit.Image
            };
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult EditSection(UpdateSectionDTO model)
        {
            if (model.Image?.Base64 == "defaultBase64Value" && model.Image?.Extension == "defaultExtension")
            {
                model.Image = null;
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var result = _sectionService.Update(model);
            if (result == null)
            {
                return RedirectToAction("SectionsAndTopicsList", new { sectionId = model.Parent.Id });
            }
            else
            {
                TempData["ErrorMessage"] = "Section of this id not found";
                return RedirectToAction("Error", "Home");
            }
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> AddTopic(int sectionId)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var result = _banService.GetActiveBan(currentUser.Id);
            if (result != null)
            {
                TempData["ErrorMessage"] = "You are blocked you cannot actually add new topic.";
                return RedirectToAction("Error", "Home");
            }
            var rootSectionResult = _sectionService.GetRootSection();
            if (!rootSectionResult.IsSuccess)
            {

MotoVernal/Views/Forum/addSection.cshtml
@model BusinessLogic.DTO.Section.AddSectionDTO;
@{
    ViewData["Title"] = "Forum - Add Section";
}
@section Styles {
    <link rel="stylesheet" href="~/css/addEditSection.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
}
@section Scripts {
    <script src="~/js/editingImage.js"></script>
}
<div class="form-container">
    <h2>Add new section</h2>
    <form asp-action="AddSection" method="post">
        <div class="form-title">
            <input type="text" id="title" placeholder="Title of the section" asp-for="Title">
        </div>
        <div class="validate">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-category">
            <div class="category-image">
                <label for="category">Parent category</label>

            </div>
            <div class="category-list" id="category-list">
                <span>@Model.Parent.Title</span>
            </div>
            <input type="hidden" asp-for="Parent.Id" value="@Model.Parent.Id" />
            <input type="hidden" asp-for="Parent.Title" value="@Model.Parent.Title" />
        </div>

        <div class="form-group image-upload">
            <label for="photo-select__file" class="load-image-label">Load image</label>
            <input id="photo-select__file" type="file" accept="image/*" style="display: none;">

            <div class="current-image" style="display: @(!string.IsNullOrEmpty(Model.Image?.Base64) ? "block" : "none")">
                <img id="image-preview" src="@(string.IsNullOrEmpty(Model.Image?.Base64) ? "" : $"data:image/{Model.Image.Extension};base64,{Model.Image.Base64}")" alt="Preview of uploaded image" style="width: 200px; height: auto;">
            </div>

            <input type="hidden" id="base64" name="Image.Base64" asp-for="Image.Base64" value="@Model.Image?.Base64" />
            <input type="hidden" id="extension" name="Image.Extension" asp-for="Image.Extension" value="@Model.Image?.Extension" />
        </div>

        <div class="form-actions">
            <button type="button" class="cancel-btn" onclick="window.location.href='/Forum/SectionsAndTopicsList?sectionId=@Model.Parent.Id'">Cancel</button>
            <button type="submit" class="create-btn">Create</button>
        </div>
    </form>
</div>

MotoVernal/Views/Forum/addTopic.cshtml
@model BusinessLogic.DTO.Topic.AddTopicDTO;
@{
    ViewData["Title"] = "Forum - Add Topic";
}
@section Styles {
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/addEditEventPostTopic.css" />
}
@section Scripts {
    <script src="~/js/editingImage.js"></script>
}
<div class="form-container">
    <form asp-action="AddTopic" method="post">
        <input type="hidden" asp-for="Publisher.Id" value="@Model.Publisher.Id" />
        <h2>Add new topic</h2>
        <div class="section-title">
            <label for="category">in @Model.Section.Title Section</label>
            <input type="hidden" asp-for="Section.Id" value="@Model.Section.Id" />
            <input type="hidden" asp-for="Section.Title" value="@Model.Section.Title" />    
        </div>
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" asp-for="Title">
        </div>
        <div class="validate">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" rows="5" cols="45" placeholder="Enter description" asp-for="Description" ></textarea>
        </div>
        <div class="validate">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group image-upload">
            <label for="photo-select__file" class="load-image-label">Load image</label>
            <input id="photo-select__file" type="file" accept="image/*" style="display: none;">

            <div class="current-image" style="display: @(!string.IsNullOrEmpty(Model.Image?.Base64) ? "block" : "none")">
                <img id="image-preview" src="@(string.IsNullOrEmpty(Model.Image?.Base64) ? "" : $"data:image/{Model.Image.Extension};base64,{Model.Image.Base64}")" alt="Preview of uploaded image" style="width: 200px; height: auto;">
            </div>

            <input type="hidden" id="base64" name="Image.Base64" asp-for="Image.Base64" value="@Model.Image?.Base64" />
            <input type="hidden" id="extension" name="Image.Extension" asp-for="Image.Extension" value="@Model.Image?.Extension" />
        </div>
        <div class="form-actions">
            <button type="button" class="cancel-btn" onclick="window.location.href='/Forum/SectionsAndTopicsList?sectionId=@Model.Section.Id'">Cancel</button>
            <button type="submit" class="create-btn">Public</button>
        </div>
    </form>
</div>

MotoVernal/Views/Forum/detailsTopic.cshtml
@inject BusinessLogic.Services.Interfaces.IUserService userService;
@model MotoVernal.ViewModels.TopicDetailsViewModel;
@{
    ViewData["Title"] = "Forum - Details Topic";
    var userId = userService.GetCurrentUser().Result.Id;
}
@section Styles {
    <link rel="stylesheet" href="~/css/detailsTopic.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
}
@section Scripts {
    <script src="~/js/addingImage.js"></script>
    <script src="~/js/topicResponseReaction.js"></script>
}
<div class="main-cnt">
    <input type="hidden" class="user-id" value="@userId" />
    <div class="basic-info">
        <span>@Model.TopicInfo.Title</span>
        <div class="extra-info">
            <button class="profile" onclick="window.location.href='/user/ProfileView?id=@Model.TopicInfo.Publisher.Id'">
                @if (Model.TopicInfo.Publisher.ProfileImage != null && !string.IsNullOrEmpty(Model.TopicInfo.Publisher.ProfileImage.Base64) && !string.IsNullOrEmpty(Model.TopicInfo.Publisher.ProfileImage.Extension))
                {
                    <img class="profil-img" src="data:image/@Model.TopicInfo.Publisher.ProfileImage.Extension;base64,@Model.TopicInfo.Publisher.ProfileImage.Base64" />
                }
                else
                {
                    <img src="~/images/profilowe.jpg" id="profil-img" alt="profil" class="profil-img">
                }
            </button>
            <span class="nickname">@Model.TopicInfo.Publisher.UserName</span>
            <img src="~/images/stopwatch.png" alt="stopwatch-img" class="stopwatch-img">
            <span class="hour">@Model.TopicInfo.CreationTime.ToString("HH:mm")</span>
            <span class="date">@Model.TopicInfo.CreationTime.ToString("dd-MM-yyyy")</span>
            <button class="go-back" onclick="window.location.href='/Forum/SectionsAndTopicsList?sectionId=@Model.TopicInfo.Section.Id'">
                <img src="~/images/undo.png" alt="go_back-img" class="go-back-img">
            </button>
        </div>
    </div>
    <div class="main-info">
        <div class="description-info-item">
            <span>
                <pre>@Model.TopicInfo.Description</pre>
            </span>
        </div>
        @if (Model.TopicInfo.Image != null && !string.IsNullOrEmpty(Model.TopicInfo.Image.Base64) && !string.IsNullOrEmpty(Model.TopicInfo.Image.Extension))
        {
            <img alt="topic-img" class="topic-img" src="data:image/@Model.TopicInfo.Image.Extension;base64,@Model.TopicInfo.Image.Base64" />
        }
        else
        {
            <img src="~/images/default_car.png" id="topic-img" alt="topic-img" class="topic-img">
        }
        <div class="action-buttons">
            @if (ViewBag.isOwner)
            {
                <button class="edit-button" onclick="window.location.href='/Forum/EditTopic?id=@Model.TopicInfo.Id'">
                    <label>Edit</label>
                    <img src="~/images//draw.png" alt="edit" class="edit-image" id="edit-image">
                </button>
            }
        </div>
    </div>
    <div class="line">
    </div>
    <div id="commentsWindow" class="commentsWindow">
        @foreach (var comment in Model.Responses)
        {
            <div class="comments-content"
                 response-id="@comment.Id"
                 reaction-state="@(comment.UserResponse?.ReactionType.ToString().ToLower() ?? "none")"
                @(comment.UserResponse != null ? $"reaction-id={comment.UserResponse.Id}" : "")>
                @if (ViewBag.CurrentUserId == comment.Owner.Id)
                {
                    <button id="edit-comment-btn" class="edit-comment-btn">
                        <img src="~/images/draw.png" alt="edit" class="edit-icon">
                    </button>
                    <button id="cancel-edit-btn" class="cancel-edit-btn">
                        <img src="~/images/x-button.png" alt="cancel" class="cancel-icon">
                    </button>
                }
                else
                {
                    <button style="display: none" id="edit-comment-btn" class="edit-comment-btn">
                        <img src="~/images/draw.png" alt="edit" class="edit-icon">
                    </button>
                    <button style="display: none" id="cancel-edit-btn" class="cancel-edit-btn">
                        <img src="~/images/x-button.png" alt="cancel" class="cancel-icon">
                    </button>
                }
                <div class="main-post">
                    <div class="post-info">
                        <div class="profile">
                            <button class="profile-btn" onclick="window.location.href='/user/ProfileView?id=@comment.Owner.Id'">
                                @if (comment.Owner.ProfileImage != null && !string.IsNullOrEmpty(comment.Owner.ProfileImage.Base64) && !string.IsNullOrEmpty(comment.Owner.ProfileImage.Extension))
                                {
                                    <img class="profil-img" src="data:image/@comment.Owner.ProfileImage.Extension;base64,@comment.Owner.ProfileImage.Base64" />
                                }
                                else
                                {
                                    <img src="~/images/profilowe.jpg" id="profil-img" alt="profil" class="profil-img">
                                }
                            </button>
                            <span>@comment.Owner.UserName</span>
                        </div>
                        <div class="create-time">
                            <img src="~/images/clock.png" alt="clock" class="clock-icon" id="clock-icon">
                            <div class="date">
                                <span>@comment.CreationTime.ToString("HH:mm")</span>
                                <label>@comment.CreationTime.ToString("dd-MM-yyyy")</label>
                            </div>
                        </div>
                    </div>
                    <form class="editable-post-content" asp-action="EditResponse" asp-route-id="@comment.Id" method="post">
                        <span id="editable-content" class="editable-content">
                            @comment.Description
                        </span>
                        <textarea class="editable-post-content__description" name="Description"></textarea>
                        <div class="image-upload">
                            <label for="photo-select__file" class="load-image-label">Load image</label>
                            <input class="photo-select__file" type="file" accept="image/*" style="display: none;">

                            <div class="current-image" style="display: @(!string.IsNullOrEmpty(comment.Image?.Base64) ? "block" : "none")">
                                <img src="@(string.IsNullOrEmpty(comment.Image?.Base64) ? "" : $"data:image/{comment.Image.Extension};base64,{comment.Image.Base64}")" alt="Preview of uploaded image">
                            </div>
                            <input type="hidden" class="base64" name="Image.Base64" value="@comment.Image?.Base64" />
                            <input type="hidden" class="extension" name="Image.Extension" value="@comment.Image?.Extension" />
                        </div>
                    </form>
                    <div class="line-2">
                    </div>

                    <div class="action-group">
                        <div class="interacted-group">
                            <button class="like-btn">
                                <img src="~/images/like.png" alt="like" class="like-icon" id="like-image">
                            </button>
                            <span class="like-count">@comment.LikeCount</span>
                            <button class="dislike-btn">
                                <img src="~/images/dislike.png" alt="dislike" class="dislike-icon" id="dislike-image">
                            </button>
                            <span class="dislike-count">@comment.DisLikeCount</span>
                        </div>
                    </div>
                </div>
                @if (ViewBag.CurrentUserId == comment.Owner.Id || User.IsInRole("Admin"))
                {
                    <form action="@Url.Action("DeleteComment", "Forum", new { commentId = comment.Id })" method="post">
                    <button class="x-btn">
                        <img src="~/images/trash-bin.png" alt="delete" class="x-icon" id="x-image">
                    </button>
                    </form>
                }
            </div>
        }
        <div class="add-comment-content">
            <form asp-action="AddResponse" method="post">
                <input type="hidden" name="Topic.Id" asp-for="ResponseToAdd.Topic.Id" value="@Model.ResponseToAdd.Topic.Id" />
                <input type="hidden" name="Owner.Id" asp-for="ResponseToAdd.Owner.Id" value="@Model.ResponseToAdd.Owner.Id" />
                <button id="edit-comment-btn" class="edit-comment-btn">
                    <img src="~/images/draw.png" alt="edit" class="edit-icon" id="edit-icon">
                </button>
                <div class="main-post">
                    <div class="post-content">
                        <textarea id="comment-textarea" placeholder="Write to comment" name="Description" asp-for="ResponseToAdd.Description"></textarea>
                        <div class="image-upload">
                            <label for="photo-select__file" id="load_image_in_add" class="load-image-label">Load image</label>
                            <input class="photo-select__file" type="file" accept="image/*" style="display: none;">

                            <div id="current-image" class="current-image" style="display: @(!string.IsNullOrEmpty(Model.ResponseToAdd.Image?.Base64) ? "block" : "none")" >
                                <img id="image-preview" src="@(string.IsNullOrEmpty(Model.ResponseToAdd.Image?.Base64) ? "" : $"data:image/{Model.ResponseToAdd.Image.Extension};base64,{Model.ResponseToAdd.Image.Base64}")" alt="Preview of uploaded image">
                            </div>
                            <input type="hidden" class="base64" name="Image.Base64" asp-for="ResponseToAdd.Image.Base64" value="@Model.ResponseToAdd.Image?.Base64" />
                            <input type="hidden" class="extension" name="Image.Extension" asp-for="ResponseToAdd.Image.Extension" value="@Model.ResponseToAdd.Image?.Extension" />
                        </div>
                    </div>
                    <div class="line-2" id="line_in_add" style="display:none;">
                    </div>
                    <div id="new-comment-action" class="comment-action">
                        <button type="button" id="cancel-btn" class="cancel-btn">
                            <span>Cancel</span>
                        </button>
                        <button type="submit" class="comment-btn">
                            <span>Comment</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

MotoVernal/Views/Forum/editSection.cshtml
@model BusinessLogic.DTO.Section.UpdateSectionDTO;
@{
    ViewData["Title"] = "Forum - Edit Section";
}
@section Styles {
    <link rel="stylesheet" href="~/css/addEditSection.css" />
}
@section Scripts {
    <script src="~/js/editingImage.js"></script>
}
<div class="form-container">
    <h2>Edit section</h2>
    <form asp-action="EditSection" method="post">
        <input type="hidden" asp-for="Id" />
        <div class="form-title">
            <input type="text" id="title" placeholder="Title of the section" asp-for="Title">
        </div>
        <div class="validate">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="form-category">
            <div class="category-image">
                <label for="category">Parent category</label>

            </div>
            <div class="category-list" id="category-list">
                <span>@Model.Parent.Title</span>
            </div>
            <input type="hidden" asp-for="Parent.Id" value="@Model.Parent.Id" />
            <input type="hidden" asp-for="Parent.Title" value="@Model.Parent.Title" />
        </div>

        <div class="form-group image-upload">
            <label for="photo-select__file" class="load-image-label">Load image</label>
            <input id="photo-select__file" type="file" accept="image/*" style="display: none;">

            <div class="current-image" style="display: @(!string.IsNullOrEmpty(Model.Image?.Base64) ? "block" : "none")">
                <img id="image-preview" src="@(string.IsNullOrEmpty(Model.Image?.Base64) ? "" : $"data:image/{Model.Image.Extension};base64,{Model.Image.Base64}")" alt="Preview of uploaded image" style="width: 200px; height: auto;">
            </div>

            <input type="hidden" id="base64" name="Image.Base64" asp-for="Image.Base64" value="@Model.Image?.Base64" />
            <input type="hidden" id="extension" name="Image.Extension" asp-for="Image.Extension" value="@Model.Image?.Extension" />
        </div>

        <div class="form-actions">
            <button type="button" class="cancel-btn" onclick="window.location.href='/Forum/SectionsAndTopicsList?sectionId=@Model.Parent.Id'">Cancel</button>
            <button type="submit" class="create-btn">Save changes</button>
        </div>
    </form>
</div>