MotoVernal/Controllers/CalendarController.cs
using BusinessLogic.DTO.Event;
using BusinessLogic.DTO.EventInterest;
using BusinessLogic.Errors;
using BusinessLogic.Services.Interfaces;
using DB.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MotoVernal.ViewModels;

namespace MotoVernal.Controllers
{
    public class CalendarController : Controller
    {
        private readonly IEventService _eventService;
        private readonly IBanService _banService;
        private readonly UserManager<User> _userManager;

        public CalendarController(IEventService eventService, IBanService banService, UserManager<User> userManager)
        {
            _eventService = eventService;
            _banService = banService;
            _userManager = userManager;
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EventsList(string sortBy, string search, DateTime? dateFrom, DateTime? dateTo, bool? owner, bool? interested, string location)
        {
            var currentUser = await _userManager.GetUserAsync(User);
            var events = _eventService.GetEvents();
            var locations = events
               .Select(e => e.Location)
               .Distinct()
               .ToList();
            if (owner.HasValue && owner.Value)
                events = events.Where(e => e.Publisher == currentUser).ToList();
            if (interested.HasValue && interested.Value)
                events = events.Where(e => _eventService.GetAllInterestByEvent(e.Id).Any(i => i.User == currentUser)).ToList();
            if (!string.IsNullOrEmpty(location))
                events = events.Where(e => e.Location == location).ToList();
            if (dateFrom.HasValue)
                events = events.Where(e => e.TimeFrom >= dateFrom.Value).ToList();
            if (dateTo.HasValue)
                events = events.Where(e => e.TimeTo <= dateTo.Value).ToList();
            if (!string.IsNullOrEmpty(search))
            {
                events = events.Where(e =>
                    e.Title.Contains(search, StringComparison.OrdinalIgnoreCase) ||
                    e.Publisher.UserName.Contains(search, StringComparison.OrdinalIgnoreCase)
                ).ToList();
            }
            switch (sortBy)
            {
                case "alphabetical_asc":
                    events = events.OrderBy(e => e.Title).ToList();
                    break;
                case "alphabetical_desc":
                    events = events.OrderByDescending(e => e.Title).ToList();
                    break;
                case "date_asc":
                    events = events.OrderBy(e => e.TimeFrom).ToList();
                    break;
                case "date_desc":
                    events = events.OrderByDescending(e => e.TimeFrom).ToList();
                    break;
                default:
                    events = events.OrderBy(e => e.TimeFrom).ToList();
                    break;
            }
            var eventsWithInterest = events.Select(e => new EventDTO
            {
                Id = e.Id,
                Publisher = e.Publisher,
                Title = e.Title,
                Description = e.Description,
                Location = e.Location,
                TimeFrom = e.TimeFrom,
                TimeTo = e.TimeTo,
                Image = e.Image,
                InterestedList = _eventService.GetAllInterestByEvent(e.Id)
            }).ToList();
            ViewBag.Locations = locations;
            ViewBag.DateFrom = dateFrom?.ToString("yyyy-MM-ddTHH:mm");
            ViewBag.DateTo = dateTo?.ToString("yyyy-MM-ddTHH:mm");
            ViewBag.SortBy = sortBy;
            ViewBag.Search = search;
            ViewBag.Owner = owner;
            ViewBag.Interested = interested;
            ViewBag.SelectedLocation = location;
            return View(eventsWithInterest);
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> AddEvent()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var result = _banService.GetActiveBan(currentUser.Id);
            if (result != null)
            {
                TempData["ErrorMessage"] = "You are blocked you cannot actually plan new event.";
                return RedirectToAction("Error", "Home");
            }
            var model = new AddEventDTO
            {
                Publisher = currentUser,
                EventType = DB.Enums.EventType.Physical,
                TimeFrom = DateTime.Today,
                TimeTo = DateTime.Today.AddDays(1),
                Title = string.Empty,
                Location = string.Empty,
                Description = string.Empty,
                Image = null
            };
            return View(model);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddEvent(AddEventDTO model)
        {
            var currentUser = await _userManager.FindByIdAsync(model.Publisher.Id);
            model.Publisher = currentUser;
            if (model.Image?.Base64 == "defaultBase64Value" && model.Image?.Extension == "defaultExtension")
            {
                model.Image = null;
            }
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var isBanned = _banService.GetActiveBan(currentUser.Id);
            if (isBanned != null)
            {
                TempData["ErrorMessage"] = "You are blocked you cannot actually plan new event.";
                return RedirectToAction("Error", "Home");
            }
            _eventService.Add(model);
            return RedirectToAction("EventsList");
        }
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> EditEvent(int id)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            var resultBan = _banService.GetActiveBan(currentUser.Id);
            if (resultBan != null)
            {
                TempData["ErrorMessage"] = "You are blocked you cannot edit your event.";
                return RedirectToAction("Error", "Home");
            }
            var result = _eventService.Get(id);

            var currentUserId = _userManager.GetUserId(User);
            if (result.Value == null)
            {
                TempData["ErrorMessage"] = "Event not exist";
                return RedirectToAction("Error", "Home");
            }
            else if (currentUserId != result.Value.Publisher.Id)
            {
                TempData["ErrorMessage"] = "You are not a owner of this event";
                return RedirectToAction("Error", "Home");
            }
            var model = new UpdateEventDTO
            {
                Id = id,
                EventType = result.Value.EventType,
                TimeFrom = result.Value.TimeFrom,
                TimeTo = result.Value.TimeTo,
                Title = result.Value.Title,
                Location = result.Value.Location,
                Description = result.Value.Description,
                Image = result.Value.Image
            };
            return View(model);
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> EditEvent(UpdateEventDTO updateEventDTO)
        {
            if (updateEventDTO.Image?.Base64 == "defaultBase64Value" && updateEventDTO.Image?.Extension == "defaultExtension")
            {
                updateEventDTO.Image = null;
            }
            if (!ModelState.IsValid)
            {
                return View(updateEventDTO);
            }
            var currentUser = await _userManager.GetUserAsync(User);

            var resultBan = _banService.GetActiveBan(currentUser.Id);
            if (resultBan != null)
            {
                TempData["ErrorMessage"] = "You are blocked you cannot edit your event.";
                return RedirectToAction("Error", "Home");
            }
            var result = _eventService.Get(updateEventDTO.Id);
            if (result.Value == null)
            {
                TempData["ErrorMessage"] = "Event not exist";
                return RedirectToAction("Error", "Home");
            }
            else if (currentUser.Id != result.Value.Publisher.Id)
            {
                TempData["ErrorMessage"] = "You are not a owner of this event";
                return RedirectToAction("Error", "Home");
            }

            _eventService.Update(updateEventDTO.Id, updateEventDTO);
            return RedirectToAction("DetailsEvent", new { id = updateEventDTO.Id });
        }

        [Authorize]
        [HttpGet]
        public IActionResult DetailsEvent(int Id)
        {
            var result = _eventService.Get(Id);
            var interestedUsers = _eventService.GetAllInterestByEvent(Id);

            ViewBag.EventID = Id;

            var currentUserId = _userManager.GetUserId(User);
            bool isCurrentUserInterested = interestedUsers.Any(u => u.User.Id == currentUserId);

            ViewBag.IsCurrentUserInterested = isCurrentUserInterested;
            if (result.Value != null)
            {
                bool isOwner = currentUserId == result.Value.Publisher.Id;
                ViewBag.isOwner = isOwner;
                var viewModel = new EventDetailsViewModel
                {
                    EventDetails = result.Value,
                    InterestedUsers = interestedUsers
                };
                return View(viewModel);
            }
            else if (result.Error == EventErrorCode.EventNotFound)
            {
                TempData["ErrorMessage"] = "Event not exist";
                return RedirectToAction("Error", "Home");
            }
            return View();
        }
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> InterestEvent(int id)
        {
            var currentUser = await _userManager.GetUserAsync(User);

MotoVernal/Views/Calendar/addEvent.cshtml
@model BusinessLogic.DTO.Event.AddEventDTO;
@{
    ViewData["Title"] = "Calendar - Plan Event";
}
@section Styles {
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/addEditEventPostTopic.css" />
}
@section Scripts {
    <script src="~/js/editingImage.js"></script>
}
<div class="form-container">
    <form asp-action="AddEvent" method="post">
        <input type="hidden" asp-for="Publisher.Id" value="@Model.Publisher.Id" />
        <h2>Plan new event</h2>
        <div class="form-group" id="select">
            <label for="type">Type</label>
            <select id="type" asp-for="EventType">
                @foreach (var eventType in Enum.GetValues(typeof(DB.Enums.EventType)).Cast<DB.Enums.EventType>())
                {
                    <option value="@eventType">
                        @eventType
                    </option>
                }
            </select>
        </div>
        <div class="validate">
            <span asp-validation-for="EventType" class="text-danger"></span>
        </div>
        <div class="date-group">
            <div class="form-control">
                <label for="datetime-from">Date from</label>
                <input type="datetime-local" id="datetime-from" asp-for="TimeFrom">
            </div>
            <div class="form-control">
                <label for="datetime-to">Date to</label>
                <input type="datetime-local" id="datetime-to" asp-for="TimeTo">
            </div>
        </div>
        <div class="date-group">
            <span asp-validation-for="TimeFrom" class="text-danger"></span>
            <span asp-validation-for="TimeTo" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" asp-for="Title">
        </div>
        <div class="validate">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="description">Description</label>
            <textarea id="description" rows="4" placeholder="Enter description" asp-for="Description"></textarea>
        </div>
        <div class="validate">
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="location">Location</label>
            <input type="text" asp-for="Location">
        </div>
        <div class="validate">
            <span asp-validation-for="Location" class="text-danger"></span>
        </div>
        <div class="form-group image-upload">
            <label for="photo-select__file" class="load-image-label">Load image</label>
            <input id="photo-select__file" type="file" accept="image/*" style="display: none;">

            <div class="current-image" style="display: @(!string.IsNullOrEmpty(Model.Image?.Base64) ? "block" : "none")">
                <img id="image-preview" src="@(string.IsNullOrEmpty(Model.Image?.Base64) ? "" : $"data:image/{Model.Image.Extension};base64,{Model.Image.Base64}")" alt="Preview of uploaded image" style="width: 200px; height: auto;">
            </div>

            <input type="hidden" id="base64" name="Image.Base64" asp-for="Image.Base64" value="@Model.Image?.Base64" />
            <input type="hidden" id="extension" name="Image.Extension" asp-for="Image.Extension" value="@Model.Image?.Extension" />
        </div>

        <div class="form-actions">
            <button type="button" class="cancel-btn" onclick="window.location.href='/Calendar/EventsList'">Cancel</button>
            <button type="submit" class="create-btn">Create</button>
        </div>
    </form>
</div>

MotoVernal/Views/Calendar/detailsEvent.cshtml
@model MotoVernal.ViewModels.EventDetailsViewModel;
@{
    ViewData["Title"] = "Calendar - Details Event";
}
@section Styles {
    <link rel="stylesheet" href="~/css/detailsEvent.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
}
@section Scripts {
    <script src="~/js/detailsEvent.js"></script>
}
<div class="main-cnt">
    <div class="info-container">
        <label>@Model.EventDetails.Title</label>
        <div class="main-info">
            <div class="description">
                <span>
                    <pre>@Model.EventDetails.Description</pre>
                </span>
            </div>
            <div class="rest-group">
                @if (Model.EventDetails.Image != null && !string.IsNullOrEmpty(Model.EventDetails.Image.Base64) && !string.IsNullOrEmpty(Model.EventDetails.Image.Extension))
                {
                    <img alt="car" class="car-image" src="data:image/@Model.EventDetails.Image.Extension;base64,@Model.EventDetails.Image.Base64" />
                }
                else
                {
                    <img src="~/images/default_car.png" id="car-img" alt="car-ing" class="car-img">
                }
                @if (ViewBag.isOwner)
                {
                    <button class="edit-button" onclick="window.location.href='/Calendar/EditEvent?id=@ViewBag.EventID'">
                        <label>Edit</label>
                        <img style="filter: invert(1)" src="~/images/edit-icon.svg" alt="edit" class="edit-image" id="edit-image" width="35px" height="35px">
                    </button>
                }
            </div>
        </div>
        <div class="event-content">
            <label>by</label>
            <button class="profil-btn" id="profil-button" onclick="window.location.href='/user/ProfileView?id=@Model.EventDetails.Publisher.Id'">
                @if (Model.EventDetails.Publisher.ProfileImage != null && !string.IsNullOrEmpty(Model.EventDetails.Publisher.ProfileImage.Base64) && !string.IsNullOrEmpty(Model.EventDetails.Publisher.ProfileImage.Extension))
                {
                    <img class="profil-img" src="data:image/@Model.EventDetails.Publisher.ProfileImage.Extension;base64,@Model.EventDetails.Publisher.ProfileImage.Base64" />
                }
                else
                {
                    <img src="~/images/profilowe.jpg" id="profil-img" alt="profil" class="profil-img">
                }
            </button>
            <label>@Model.EventDetails.Publisher.UserName</label>
        </div>
        <div class="event-content">
            <label>@Model.EventDetails.Location</label>
            <img src="~/images/pin.png" alt="pin" class="pin-image" id="pin-image">
        </div>
        <div class="event-content">
            <label>From</label>
            <label class="hour">@Model.EventDetails.TimeFrom.ToString("HH:mm")</label>
            <label class="date">@Model.EventDetails.TimeFrom.ToString("dd-MM-yyyy")</label>
            <img src="~/images/calendar.png" alt="calendar" class="calendar-image" id="calendar-image">
            <label>To</label>
            <label class="hour">@Model.EventDetails.TimeTo.ToString("HH:mm")</label>
            <label class="date">@Model.EventDetails.TimeTo.ToString("dd-MM-yyyy")</label>
            <img src="~/images/calendar.png" alt="calendar" class="calendar-image" id="calendar-image">
        </div>
        
        <div class="interested-section">
            <div class="interested-header">
                <img src="~/images/group.png" alt="group" class="group-image" id="group-image">
                <span>@Model.InterestedUsers.Count Interested</span>
                <button id="toggle-list">▼</button>
            </div>
            <ol class="interested-list hidden">
                @foreach (var userInterest in Model.InterestedUsers)
                {
                <li>
                    <span>▷</span>
                        <button class="profil-btn" id="profil-button" onclick="window.location.href='/user/ProfileView?id=@userInterest.User.Id'">
                            @if (userInterest.User.ProfileImage != null && !string.IsNullOrEmpty(userInterest.User.ProfileImage.Base64) && !string.IsNullOrEmpty(userInterest.User.ProfileImage.Extension))
                            {
                                <img class="profil-img" src="data:image/@userInterest.User.ProfileImage.Extension;base64,@userInterest.User.ProfileImage.Base64" />
                            }
                            else
                            {
                                <img src="~/images/profilowe.jpg" id="profil-img" alt="profil" class="profil-img">
                            }
                        </button>
                    <span>@userInterest.User.UserName</span>
                </li>
                }
            </ol>
        </div>
        <div class="details-action">
            <button class="go-back" onclick="window.location.href='/Calendar/EventsList'">
                <span>Take me back</span>
            </button>
            @if (!ViewBag.isOwner)
            {
            @if (ViewBag.IsCurrentUserInterested)
            {
                <form asp-action="UninterestEvent" method="post">
                    <input type="hidden" name="id" value="@ViewBag.EventID" />
                    <button class="interested-btn interested">
                        <span>You are interested</span>
                    </button>
                </form>
            }
            else
            {
                <form asp-action="InterestEvent" method="post">
                    <input type="hidden" name="id" value="@ViewBag.EventID" />
                    <button class="show-more">
                        <span>I'm interested</span>
                    </button>
                </form>
            }
            }
        </div>
    </div>
</div>

MotoVernal/Views/Calendar/eventsList.cshtml
@model List<BusinessLogic.DTO.Event.EventDTO>
@{
    ViewData["Title"] = "Calendar - Events List";
}
@section Styles {
    <link rel="stylesheet" href="~/css/eventsList.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
}
@section Scripts {
    <script src="~/js/eventsList.js"></script>
}
<form method="get" action="@Url.Action("EventsList", "Calendar")" class="eventsList">
    <section>
        <div>
            <div class="up-section">
                <div class="nav-tree">
                    <label for="place">Calendar</label>
                </div>
            </div>
            <div class="second-section">
                <div class="filter-by">
                    <label>Filter by</label>
                        <button class="clear" id="clear-filters-btn">
                        <span>X Clear All</span>
                    </button>
                </div>
                <div class="search-bar">
                    <button type="submit">
                        <img src="~/images/peel.svg" alt="peel" class="peel-icon" id="peel-icon">
                    </button>
                    <input type="text" name="search" value="@ViewBag.search" id="search" placeholder="Search">
                </div>
                <div class="filter-group">
                    <div class="filter-group__header">
                        Date
                    </div>
                    <div class="filter-group__content">
                        <div class="date-group">
                            <label for="datetime-from" ></label>
                            <input type="datetime-local" id="datetime-from" name="dateFrom" value="@ViewBag.DateFrom" onchange="this.form.submit()">
                        </div>
                        <div class="date-group">
                            <label for="datetime-to"></label>
                            <input type="datetime-local" id="datetime-to" name="dateTo" value="@ViewBag.DateTo" onchange="this.form.submit()">
                        </div>
                    </div>
                </div>
                <div class="location-group">
                    <label for="location">Location</label>
                    <select id="location" class="location"name="location" onchange="this.form.submit()">
                        <option value="">-- Select Location --</option>
                        @foreach (var loc in ViewBag.Locations as List<string>)
                        {
                            @if (ViewBag.SelectedLocation == loc)
                            {
                                <option value="@loc" selected>@loc</option>
                            }
                            else
                            {
                                <option value="@loc">@loc</option>
                            }
                        }
                    </select>
                </div>
                <div class="location-group">
                    <label for="status">Status</label>
                    <div class="status-groups">
                        <div class="status-group">
                            <label class="status">Owner</label>
                            <input type="checkbox" id="owner" name="owner" value="true"
                            @(ViewBag.Owner == true ? "checked" : "") onchange="this.form.submit()">
                        </div>
                        <div class="status-group">
                            <label class="status">Interested</label>
                            <input type="checkbox" id="interested" name="interested" value="true"
                            @(ViewBag.Interested == true ? "checked" : "") onchange="this.form.submit()">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="main-cnt">
        <div class="main-cnt__header">
            <div class="adding-section">
                <button type="button" class="add-section" onclick="window.location.href='/Calendar/AddEvent'">
                    Plan new event
                </button>
            </div>
            <div class="sort">
                <label for="sort_by">Sort By</label>
                <select id="sortBy" name="sortBy" onchange="this.form.submit()">
                    @if (ViewBag.SortBy == "date_asc")
                    {
                        <option value="date_asc" selected>Date ASC</option>
                    }
                    else
                    {
                        <option value="date_asc">Date ASC</option>
                    }

                    @if (ViewBag.SortBy == "date_desc")
                    {
                        <option value="date_desc" selected>Date DESC</option>
                    }
                    else
                    {
                        <option value="date_desc">Date DESC</option>
                    }

                    @if (ViewBag.SortBy == "alphabetical_asc")
                    {
                        <option value="alphabetical_asc" selected>Alphabetical ASC</option>
                    }
                    else
                    {
                        <option value="alphabetical_asc">Alphabetical ASC</option>
                    }

                    @if (ViewBag.SortBy == "alphabetical_desc")
                    {
                        <option value="alphabetical_desc" selected>Alphabetical DESC</option>
                    }
                    else
                    {
                        <option value="alphabetical_desc">Alphabetical DESC</option>
                    }
                </select>
            </div>
        </div>
        <div class="main-cnt__inner">
            <ul>
                @foreach (var ev3nt in Model)
                {
                    <li>
                        @if (ev3nt.Image != null && !string.IsNullOrEmpty(ev3nt.Image.Base64) && !string.IsNullOrEmpty(ev3nt.Image.Extension))
                        {
                            <img alt="car" class="event-image" src="data:image/@ev3nt.Image.Extension;base64,@ev3nt.Image.Base64" />
                        }
                        else
                        {
                            <img src="~/images/default_car.png" id="event-img" alt="event" class="event-img">
                        }
                        <div class="event-info">
                            <label>
                                @ev3nt.Title
                            </label>
                            <div class="event-content">
                                <label>by</label>
                                <button class="profil-btn" id="profil-button" onclick="window.location.href='/user/ProfileView?id=@ev3nt.Publisher.Id'">
                                    @if (ev3nt.Publisher.ProfileImage != null && !string.IsNullOrEmpty(ev3nt.Publisher.ProfileImage.Base64) && !string.IsNullOrEmpty(ev3nt.Publisher.ProfileImage.Extension))
                                    {
                                        <img class="profil-img" src="data:image/@ev3nt.Publisher.ProfileImage.Extension;base64,@ev3nt.Publisher.ProfileImage.Base64" />
                                    }
                                    else
                                    {
                                        <img src="~/images/profilowe.jpg" id="profil-img" alt="profil" class="profil-img">
                                    }
                                </button>
                                <label>@ev3nt.Publisher.UserName</label>
                            </div>
                            <div class="event-content">
                                <label>@ev3nt.Location</label>
                                <img src="~/images/pin.png" alt="pin" class="pin-image" id="pin-image">
                            </div>
                            <div class="event-content">
                                <label>From</label>
                                <label class="hour">@ev3nt.TimeFrom.ToString("HH:mm")</label>
                                <label class="date">@ev3nt.TimeFrom.ToString("dd-MM-yyyy")</label>
                                <img src="~/images/calendar.png" alt="calendar" class="calendar-image" id="calendar-image">
                                <label>To</label>
                                <label class="hour">@ev3nt.TimeTo.ToString("HH:mm")</label>
                                <label class="date">@ev3nt.TimeTo.ToString("dd-MM-yyyy")</label>
                                <img src="~/images/calendar.png" alt="calendar" class="calendar-image" id="calendar-image">
                            </div>
                            <div class="line">
                            </div>
                            <div class="event-down">
                                <div class="event-interested">
                                    <img src="~/images/group.png" alt="group" class="group-image" id="group-image">
                                    <label>@ev3nt.InterestedList.Count()</label>
                                    <label class="interested">interested</label>
                                </div>
                                <button type="button" class="event-action" onclick="window.location.href='/Calendar/detailsEvent?id=@ev3nt.Id'">
                                    <span>Show more details</span>
                                </button>
                            </div>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
</form>